game:
  # If true, Player 2 is a hardcoded Optimal Bot
  # If false, Player 2 is a Neural Network learning from scratch
  p2_deterministic: true

training:
  device: "cpu"
  num_players: 100
  train_steps: 1600
  learning_rate: 0.1
  batch_size: 32
  # log_window: 10000